"""init

Revision ID: 0584f1f4cc88
Revises: 
Create Date: 2025-12-06 22:47:06.999208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0584f1f4cc88'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_market_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.String(length=10), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('high', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('low', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('close', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('volume', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('turnover', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('change', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('change_percent', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('high >= low', name='check_high_low'),
    sa.CheckConstraint('volume >= 0', name='check_volume_positive'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'entity_id', 'date', name='uq_daily_market_data_entity_date')
    )
    op.create_index('idx_daily_market_data_cover', 'daily_market_data', ['entity_type', 'entity_id', 'date', 'close', 'change_percent', 'volume'], unique=False)
    op.create_index('idx_daily_market_data_date_range', 'daily_market_data', ['date', 'close', 'volume'], unique=False)
    op.create_index('idx_daily_market_data_entity_date', 'daily_market_data', ['entity_type', 'entity_id', 'date'], unique=False)
    op.create_index('idx_daily_market_data_entity_date_desc', 'daily_market_data', ['entity_type', 'entity_id', 'date'], unique=False)
    op.create_index(op.f('ix_daily_market_data_date'), 'daily_market_data', ['date'], unique=False)
    op.create_index(op.f('ix_daily_market_data_entity_id'), 'daily_market_data', ['entity_id'], unique=False)
    op.create_index(op.f('ix_daily_market_data_entity_type'), 'daily_market_data', ['entity_type'], unique=False)
    op.create_index(op.f('ix_daily_market_data_id'), 'daily_market_data', ['id'], unique=False)
    op.create_table('moving_average_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.String(length=10), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('ma_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('trend', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'entity_id', 'date', 'period', name='uq_moving_average_data_entity_date_period')
    )
    op.create_index('idx_moving_average_data_date_desc', 'moving_average_data', ['date'], unique=False)
    op.create_index('idx_moving_average_data_date_period', 'moving_average_data', ['date', 'period'], unique=False)
    op.create_index('idx_moving_average_data_entity_date', 'moving_average_data', ['entity_type', 'entity_id', 'date'], unique=False)
    op.create_index('idx_moving_average_data_entity_period', 'moving_average_data', ['entity_type', 'entity_id', 'period'], unique=False)
    op.create_index(op.f('ix_moving_average_data_date'), 'moving_average_data', ['date'], unique=False)
    op.create_index(op.f('ix_moving_average_data_entity_id'), 'moving_average_data', ['entity_id'], unique=False)
    op.create_index(op.f('ix_moving_average_data_entity_type'), 'moving_average_data', ['entity_type'], unique=False)
    op.create_index(op.f('ix_moving_average_data_id'), 'moving_average_data', ['id'], unique=False)
    op.create_index(op.f('ix_moving_average_data_period'), 'moving_average_data', ['period'], unique=False)
    op.create_table('period_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('days', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('days > 0', name='check_days_positive'),
    sa.CheckConstraint('weight > 0', name='check_weight_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_period_configs_active', 'period_configs', ['is_active', 'days'], unique=False)
    op.create_index(op.f('ix_period_configs_id'), 'period_configs', ['id'], unique=False)
    op.create_index(op.f('ix_period_configs_is_active'), 'period_configs', ['is_active'], unique=False)
    op.create_index(op.f('ix_period_configs_period'), 'period_configs', ['period'], unique=True)
    op.create_table('sectors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('strength_score', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('trend_direction', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('strength_score >= 0 AND strength_score <= 100', name='check_sector_strength_score_range'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sectors_type_score', 'sectors', ['type', 'strength_score'], unique=False)
    op.create_index(op.f('ix_sectors_code'), 'sectors', ['code'], unique=True)
    op.create_index(op.f('ix_sectors_id'), 'sectors', ['id'], unique=False)
    op.create_index(op.f('ix_sectors_name'), 'sectors', ['name'], unique=False)
    op.create_index(op.f('ix_sectors_type'), 'sectors', ['type'], unique=False)
    op.create_table('stocks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('market_cap', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('current_price >= 0', name='check_current_price_positive'),
    sa.CheckConstraint('market_cap >= 0', name='check_market_cap_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_stocks_market_cap', 'stocks', ['market_cap'], unique=False)
    op.create_index(op.f('ix_stocks_id'), 'stocks', ['id'], unique=False)
    op.create_index(op.f('ix_stocks_name'), 'stocks', ['name'], unique=False)
    op.create_index(op.f('ix_stocks_symbol'), 'stocks', ['symbol'], unique=True)
    op.create_table('strength_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.String(length=10), nullable=False, comment='实体类型: stock或sector'),
    sa.Column('entity_id', sa.Integer(), nullable=False, comment='实体ID'),
    sa.Column('date', sa.Date(), nullable=False, comment='计算日期'),
    sa.Column('period', sa.String(length=10), nullable=False, comment='分析周期: 5d, 10d, 20d, 30d, 60d'),
    sa.Column('score', sa.Numeric(precision=10, scale=4), nullable=False, comment='综合强度得分(0-100)'),
    sa.Column('rank', sa.Integer(), nullable=True, comment='排名'),
    sa.Column('change_rate', sa.Numeric(precision=10, scale=4), nullable=True, comment='得分变化率(%)'),
    sa.Column('strength_level', sa.String(length=20), nullable=True, comment='强度等级: weak, medium, strong, very_strong'),
    sa.Column('ma5_score', sa.Numeric(precision=10, scale=4), nullable=True, comment='5日均线得分'),
    sa.Column('ma10_score', sa.Numeric(precision=10, scale=4), nullable=True, comment='10日均线得分'),
    sa.Column('ma20_score', sa.Numeric(precision=10, scale=4), nullable=True, comment='20日均线得分'),
    sa.Column('volume_score', sa.Numeric(precision=10, scale=4), nullable=True, comment='成交量得分'),
    sa.Column('momentum_score', sa.Numeric(precision=10, scale=4), nullable=True, comment='动量得分'),
    sa.Column('avg_stock_score', sa.Numeric(precision=10, scale=4), nullable=True, comment='板块内个股平均得分'),
    sa.Column('strong_stock_ratio', sa.Numeric(precision=5, scale=4), nullable=True, comment='强势个股占比'),
    sa.Column('up_stock_ratio', sa.Numeric(precision=5, scale=4), nullable=True, comment='上涨个股占比'),
    sa.Column('volume_ratio', sa.Numeric(precision=10, scale=4), nullable=True, comment='成交量比率'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_strength_scores_date_period', 'strength_scores', ['date', 'period'], unique=False)
    op.create_index('idx_strength_scores_entity_period', 'strength_scores', ['entity_type', 'entity_id', 'period'], unique=False)
    op.create_index('idx_strength_scores_rank', 'strength_scores', ['rank'], unique=False)
    op.create_index('idx_strength_scores_score', 'strength_scores', ['score'], unique=False)
    op.create_index(op.f('ix_strength_scores_date'), 'strength_scores', ['date'], unique=False)
    op.create_index(op.f('ix_strength_scores_entity_id'), 'strength_scores', ['entity_id'], unique=False)
    op.create_index(op.f('ix_strength_scores_entity_type'), 'strength_scores', ['entity_type'], unique=False)
    op.create_index(op.f('ix_strength_scores_id'), 'strength_scores', ['id'], unique=False)
    op.create_index(op.f('ix_strength_scores_period'), 'strength_scores', ['period'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False, comment='用户唯一标识符'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='电子邮箱（登录用）'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='加密后的密码'),
    sa.Column('username', sa.String(length=50), nullable=True, comment='用户名'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='账户是否激活'),
    sa.Column('is_verified', sa.Boolean(), nullable=True, comment='邮箱是否已验证'),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True, comment='最后登录时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_created', 'users', ['created_at'], unique=False)
    op.create_index('idx_user_email', 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('email_verification_tokens',
    sa.Column('id', sa.UUID(), nullable=False, comment='令牌唯一标识符'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='用户ID'),
    sa.Column('token', sa.String(length=255), nullable=False, comment='验证令牌'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='过期时间'),
    sa.Column('is_used', sa.Boolean(), nullable=True, comment='是否已使用'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_verification_token', 'email_verification_tokens', ['token'], unique=False)
    op.create_index('idx_verification_user', 'email_verification_tokens', ['user_id'], unique=False)
    op.create_index(op.f('ix_email_verification_tokens_token'), 'email_verification_tokens', ['token'], unique=True)
    op.create_table('sector_stocks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sector_id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], ),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sector_id', 'stock_id', name='uq_sector_stock')
    )
    op.create_index('idx_sector_stocks_sector', 'sector_stocks', ['sector_id', 'stock_id'], unique=False)
    op.create_index('idx_sector_stocks_stock', 'sector_stocks', ['stock_id', 'sector_id'], unique=False)
    op.create_index(op.f('ix_sector_stocks_id'), 'sector_stocks', ['id'], unique=False)
    op.create_index(op.f('ix_sector_stocks_sector_id'), 'sector_stocks', ['sector_id'], unique=False)
    op.create_index(op.f('ix_sector_stocks_stock_id'), 'sector_stocks', ['stock_id'], unique=False)
    op.create_table('watchlists',
    sa.Column('id', sa.UUID(), nullable=False, comment='关注记录唯一标识符'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='用户ID（外键）'),
    sa.Column('entity_type', sa.String(length=20), nullable=False, comment="实体类型（'stock': 个股, 'sector': 板块）"),
    sa.Column('entity_id', sa.String(length=50), nullable=False, comment='实体ID（股票ID或板块ID）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='添加关注时间'),
    sa.Column('notes', sa.String(length=500), nullable=True, comment='用户备注（可选）'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_watchlist_entity', 'watchlists', ['entity_type', 'entity_id'], unique=False)
    op.create_index('idx_watchlist_user', 'watchlists', ['user_id'], unique=False)
    op.create_index('idx_watchlist_user_entity', 'watchlists', ['user_id', 'entity_type', 'entity_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_watchlist_user_entity', table_name='watchlists')
    op.drop_index('idx_watchlist_user', table_name='watchlists')
    op.drop_index('idx_watchlist_entity', table_name='watchlists')
    op.drop_table('watchlists')
    op.drop_index(op.f('ix_sector_stocks_stock_id'), table_name='sector_stocks')
    op.drop_index(op.f('ix_sector_stocks_sector_id'), table_name='sector_stocks')
    op.drop_index(op.f('ix_sector_stocks_id'), table_name='sector_stocks')
    op.drop_index('idx_sector_stocks_stock', table_name='sector_stocks')
    op.drop_index('idx_sector_stocks_sector', table_name='sector_stocks')
    op.drop_table('sector_stocks')
    op.drop_index(op.f('ix_email_verification_tokens_token'), table_name='email_verification_tokens')
    op.drop_index('idx_verification_user', table_name='email_verification_tokens')
    op.drop_index('idx_verification_token', table_name='email_verification_tokens')
    op.drop_table('email_verification_tokens')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_user_email', table_name='users')
    op.drop_index('idx_user_created', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_strength_scores_period'), table_name='strength_scores')
    op.drop_index(op.f('ix_strength_scores_id'), table_name='strength_scores')
    op.drop_index(op.f('ix_strength_scores_entity_type'), table_name='strength_scores')
    op.drop_index(op.f('ix_strength_scores_entity_id'), table_name='strength_scores')
    op.drop_index(op.f('ix_strength_scores_date'), table_name='strength_scores')
    op.drop_index('idx_strength_scores_score', table_name='strength_scores')
    op.drop_index('idx_strength_scores_rank', table_name='strength_scores')
    op.drop_index('idx_strength_scores_entity_period', table_name='strength_scores')
    op.drop_index('idx_strength_scores_date_period', table_name='strength_scores')
    op.drop_table('strength_scores')
    op.drop_index(op.f('ix_stocks_symbol'), table_name='stocks')
    op.drop_index(op.f('ix_stocks_name'), table_name='stocks')
    op.drop_index(op.f('ix_stocks_id'), table_name='stocks')
    op.drop_index('idx_stocks_market_cap', table_name='stocks')
    op.drop_table('stocks')
    op.drop_index(op.f('ix_sectors_type'), table_name='sectors')
    op.drop_index(op.f('ix_sectors_name'), table_name='sectors')
    op.drop_index(op.f('ix_sectors_id'), table_name='sectors')
    op.drop_index(op.f('ix_sectors_code'), table_name='sectors')
    op.drop_index('idx_sectors_type_score', table_name='sectors')
    op.drop_table('sectors')
    op.drop_index(op.f('ix_period_configs_period'), table_name='period_configs')
    op.drop_index(op.f('ix_period_configs_is_active'), table_name='period_configs')
    op.drop_index(op.f('ix_period_configs_id'), table_name='period_configs')
    op.drop_index('idx_period_configs_active', table_name='period_configs')
    op.drop_table('period_configs')
    op.drop_index(op.f('ix_moving_average_data_period'), table_name='moving_average_data')
    op.drop_index(op.f('ix_moving_average_data_id'), table_name='moving_average_data')
    op.drop_index(op.f('ix_moving_average_data_entity_type'), table_name='moving_average_data')
    op.drop_index(op.f('ix_moving_average_data_entity_id'), table_name='moving_average_data')
    op.drop_index(op.f('ix_moving_average_data_date'), table_name='moving_average_data')
    op.drop_index('idx_moving_average_data_entity_period', table_name='moving_average_data')
    op.drop_index('idx_moving_average_data_entity_date', table_name='moving_average_data')
    op.drop_index('idx_moving_average_data_date_period', table_name='moving_average_data')
    op.drop_index('idx_moving_average_data_date_desc', table_name='moving_average_data')
    op.drop_table('moving_average_data')
    op.drop_index(op.f('ix_daily_market_data_id'), table_name='daily_market_data')
    op.drop_index(op.f('ix_daily_market_data_entity_type'), table_name='daily_market_data')
    op.drop_index(op.f('ix_daily_market_data_entity_id'), table_name='daily_market_data')
    op.drop_index(op.f('ix_daily_market_data_date'), table_name='daily_market_data')
    op.drop_index('idx_daily_market_data_entity_date_desc', table_name='daily_market_data')
    op.drop_index('idx_daily_market_data_entity_date', table_name='daily_market_data')
    op.drop_index('idx_daily_market_data_date_range', table_name='daily_market_data')
    op.drop_index('idx_daily_market_data_cover', table_name='daily_market_data')
    op.drop_table('daily_market_data')
    # ### end Alembic commands ###
