"""create_update_history_table

Revision ID: 9935c085b34a
Revises: 2025_12_15_add_role_and_permissions
Create Date: 2025-12-25 01:32:17.127808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9935c085b34a'
down_revision: Union[str, Sequence[str], None] = '2025_12_15_add_role_and_permissions'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('update_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.String(length=50), nullable=True),
    sa.Column('update_type', sa.String(length=20), nullable=False),
    sa.Column('target_type', sa.String(length=20), nullable=True),
    sa.Column('target_id', sa.String(length=20), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('overwrite', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('records_processed', sa.Integer(), nullable=True),
    sa.Column('records_created', sa.Integer(), nullable=True),
    sa.Column('records_updated', sa.Integer(), nullable=True),
    sa.Column('records_failed', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_update_history_end_date'), 'update_history', ['end_date'], unique=False)
    op.create_index(op.f('ix_update_history_id'), 'update_history', ['id'], unique=False)
    op.create_index(op.f('ix_update_history_start_date'), 'update_history', ['start_date'], unique=False)
    op.create_index(op.f('ix_update_history_status'), 'update_history', ['status'], unique=False)
    op.create_index('ix_update_history_status_created', 'update_history', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_update_history_target_id'), 'update_history', ['target_id'], unique=False)
    op.create_index(op.f('ix_update_history_target_type'), 'update_history', ['target_type'], unique=False)
    op.create_index('ix_update_history_task_id', 'update_history', ['task_id'], unique=False)
    op.create_index('ix_update_history_type_date', 'update_history', ['update_type', 'start_date'], unique=False)
    op.create_index(op.f('ix_update_history_update_type'), 'update_history', ['update_type'], unique=False)
    op.alter_column('active_sessions', 'id',
               existing_type=sa.UUID(),
               comment='会话唯一标识',
               existing_comment='会话唯一标识符',
               existing_nullable=False)
    op.alter_column('active_sessions', 'last_activity',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='最后活动时色',
               existing_comment='最后活动时间',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('cache_entries', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='缓存条目唯一标识符',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('cache_entries', 'key',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='缓存键',
               existing_nullable=False)
    op.alter_column('cache_entries', 'value',
               existing_type=postgresql.BYTEA(),
               comment=None,
               existing_comment='缓存值',
               existing_nullable=False)
    op.alter_column('cache_entries', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='过期时间',
               existing_nullable=False)
    op.alter_column('cache_entries', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('data_update_logs', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='更新日志唯一标识符',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('data_update_logs', 'start_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='开始时间',
               existing_nullable=False)
    op.alter_column('data_update_logs', 'end_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='结束时间',
               existing_nullable=True)
    op.alter_column('data_update_logs', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='状态: success, error, running',
               existing_nullable=False)
    op.alter_column('data_update_logs', 'sectors_updated',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='更新的板块数量',
               existing_nullable=True)
    op.alter_column('data_update_logs', 'stocks_updated',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='更新的股票数量',
               existing_nullable=True)
    op.alter_column('data_update_logs', 'market_data_updated',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='更新的行情数据数量',
               existing_nullable=True)
    op.alter_column('data_update_logs', 'calculations_performed',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='执行的计算数量',
               existing_nullable=True)
    op.alter_column('data_update_logs', 'error_message',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='错误信息',
               existing_nullable=True)
    op.alter_column('data_update_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('email_verification_tokens', 'id',
               existing_type=sa.UUID(),
               comment='令牌唯一标识',
               existing_comment='令牌唯一标识符',
               existing_nullable=False)
    op.alter_column('login_attempts', 'id',
               existing_type=sa.UUID(),
               comment='登录尝试唯一标识',
               existing_comment='登录尝试唯一标识符',
               existing_nullable=False)
    op.alter_column('login_attempts', 'user_id',
               existing_type=sa.UUID(),
               comment='用户ID（登录成功时填写)',
               existing_comment='用户ID（登录成功时填写）',
               existing_nullable=True)
    op.add_column('password_reset_tokens', sa.Column('exourcepires_at', sa.DateTime(timezone=True), nullable=False, comment='过期时间'))
    op.alter_column('password_reset_tokens', 'id',
               existing_type=sa.UUID(),
               comment='令牌唯一标识',
               existing_comment='令牌唯一标识符',
               existing_nullable=False)
    op.drop_column('password_reset_tokens', 'expires_at')
    op.alter_column('refresh_tokens', 'id',
               existing_type=sa.UUID(),
               comment='刷新令牌唯一标识',
               existing_comment='刷新令牌唯一标识符',
               existing_nullable=False)
    op.alter_column('user_preferences', 'id',
               existing_type=sa.UUID(),
               comment='偏好设置唯一标识',
               existing_comment='偏好设置唯一标识符',
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               comment='用户唯一标识色',
               existing_comment='用户唯一标识符',
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment='电子邮箱（登录用色',
               existing_comment='电子邮箱（登录用）',
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='账户是否激色',
               existing_comment='账户是否激活',
               existing_nullable=True)
    op.alter_column('watchlists', 'id',
               existing_type=sa.UUID(),
               comment='关注记录唯一标识',
               existing_comment='关注记录唯一标识符',
               existing_nullable=False)
    op.alter_column('watchlists', 'entity_type',
               existing_type=sa.VARCHAR(length=20),
               comment="实体类型色stock': 个股, 'sector': 板块",
               existing_comment="实体类型（'stock': 个股, 'sector': 板块）",
               existing_nullable=False)
    op.alter_column('watchlists', 'entity_id',
               existing_type=sa.VARCHAR(length=50),
               comment='实体ID（股票ID或板块ID',
               existing_comment='实体ID（股票ID或板块ID）',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('watchlists', 'entity_id',
               existing_type=sa.VARCHAR(length=50),
               comment='实体ID（股票ID或板块ID）',
               existing_comment='实体ID（股票ID或板块ID',
               existing_nullable=False)
    op.alter_column('watchlists', 'entity_type',
               existing_type=sa.VARCHAR(length=20),
               comment="实体类型（'stock': 个股, 'sector': 板块）",
               existing_comment="实体类型色stock': 个股, 'sector': 板块",
               existing_nullable=False)
    op.alter_column('watchlists', 'id',
               existing_type=sa.UUID(),
               comment='关注记录唯一标识符',
               existing_comment='关注记录唯一标识',
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='账户是否激活',
               existing_comment='账户是否激色',
               existing_nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment='电子邮箱（登录用）',
               existing_comment='电子邮箱（登录用色',
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               comment='用户唯一标识符',
               existing_comment='用户唯一标识色',
               existing_nullable=False)
    op.alter_column('user_preferences', 'id',
               existing_type=sa.UUID(),
               comment='偏好设置唯一标识符',
               existing_comment='偏好设置唯一标识',
               existing_nullable=False)
    op.alter_column('refresh_tokens', 'id',
               existing_type=sa.UUID(),
               comment='刷新令牌唯一标识符',
               existing_comment='刷新令牌唯一标识',
               existing_nullable=False)
    op.add_column('password_reset_tokens', sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False, comment='过期时间'))
    op.alter_column('password_reset_tokens', 'id',
               existing_type=sa.UUID(),
               comment='令牌唯一标识符',
               existing_comment='令牌唯一标识',
               existing_nullable=False)
    op.drop_column('password_reset_tokens', 'exourcepires_at')
    op.alter_column('login_attempts', 'user_id',
               existing_type=sa.UUID(),
               comment='用户ID（登录成功时填写）',
               existing_comment='用户ID（登录成功时填写)',
               existing_nullable=True)
    op.alter_column('login_attempts', 'id',
               existing_type=sa.UUID(),
               comment='登录尝试唯一标识符',
               existing_comment='登录尝试唯一标识',
               existing_nullable=False)
    op.alter_column('email_verification_tokens', 'id',
               existing_type=sa.UUID(),
               comment='令牌唯一标识符',
               existing_comment='令牌唯一标识',
               existing_nullable=False)
    op.alter_column('data_update_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('data_update_logs', 'error_message',
               existing_type=sa.TEXT(),
               comment='错误信息',
               existing_nullable=True)
    op.alter_column('data_update_logs', 'calculations_performed',
               existing_type=sa.INTEGER(),
               comment='执行的计算数量',
               existing_nullable=True)
    op.alter_column('data_update_logs', 'market_data_updated',
               existing_type=sa.INTEGER(),
               comment='更新的行情数据数量',
               existing_nullable=True)
    op.alter_column('data_update_logs', 'stocks_updated',
               existing_type=sa.INTEGER(),
               comment='更新的股票数量',
               existing_nullable=True)
    op.alter_column('data_update_logs', 'sectors_updated',
               existing_type=sa.INTEGER(),
               comment='更新的板块数量',
               existing_nullable=True)
    op.alter_column('data_update_logs', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='状态: success, error, running',
               existing_nullable=False)
    op.alter_column('data_update_logs', 'end_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='结束时间',
               existing_nullable=True)
    op.alter_column('data_update_logs', 'start_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='开始时间',
               existing_nullable=False)
    op.alter_column('data_update_logs', 'id',
               existing_type=sa.INTEGER(),
               comment='更新日志唯一标识符',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('cache_entries', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('cache_entries', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='过期时间',
               existing_nullable=False)
    op.alter_column('cache_entries', 'value',
               existing_type=postgresql.BYTEA(),
               comment='缓存值',
               existing_nullable=False)
    op.alter_column('cache_entries', 'key',
               existing_type=sa.VARCHAR(length=255),
               comment='缓存键',
               existing_nullable=False)
    op.alter_column('cache_entries', 'id',
               existing_type=sa.INTEGER(),
               comment='缓存条目唯一标识符',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('active_sessions', 'last_activity',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='最后活动时间',
               existing_comment='最后活动时色',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('active_sessions', 'id',
               existing_type=sa.UUID(),
               comment='会话唯一标识符',
               existing_comment='会话唯一标识',
               existing_nullable=False)
    op.drop_index(op.f('ix_update_history_update_type'), table_name='update_history')
    op.drop_index('ix_update_history_type_date', table_name='update_history')
    op.drop_index('ix_update_history_task_id', table_name='update_history')
    op.drop_index(op.f('ix_update_history_target_type'), table_name='update_history')
    op.drop_index(op.f('ix_update_history_target_id'), table_name='update_history')
    op.drop_index('ix_update_history_status_created', table_name='update_history')
    op.drop_index(op.f('ix_update_history_status'), table_name='update_history')
    op.drop_index(op.f('ix_update_history_start_date'), table_name='update_history')
    op.drop_index(op.f('ix_update_history_id'), table_name='update_history')
    op.drop_index(op.f('ix_update_history_end_date'), table_name='update_history')
    op.drop_table('update_history')
    # ### end Alembic commands ###
