"""Add strength_score and trend_direction to Stock

Revision ID: f86d52e1be1a
Revises: 5d8e7a5b3c9f
Create Date: 2025-12-26 17:16:36.965210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f86d52e1be1a'
down_revision: Union[str, Sequence[str], None] = '5d8e7a5b3c9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add strength_score and trend_direction columns to Stock table
    op.add_column('stocks', sa.Column('strength_score', sa.Numeric(precision=10, scale=4), nullable=True, server_default='0', comment='强度得分 (0-100)'))
    op.add_column('stocks', sa.Column('trend_direction', sa.Numeric(precision=5, scale=2), nullable=True, server_default='0', comment='趋势方向: 1=上升, 0=横盘, -1=下降'))
    op.create_index('idx_stocks_strength_score', 'stocks', ['strength_score'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove strength_score and trend_direction columns from Stock table
    op.drop_index('idx_stocks_strength_score', table_name='stocks')
    op.drop_column('stocks', 'trend_direction')
    op.drop_column('stocks', 'strength_score')
    # ### end Alembic commands ###
