"""login attempts

Revision ID: d517faa26c91
Revises: f13c3f36c847
Create Date: 2025-12-13 00:10:37.607850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd517faa26c91'
down_revision: Union[str, Sequence[str], None] = 'f13c3f36c847'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_attempts',
    sa.Column('id', sa.UUID(), nullable=False, comment='登录尝试唯一标识符'),
    sa.Column('user_id', sa.UUID(), nullable=True, comment='用户ID（登录成功时填写）'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='尝试登录的邮箱'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='IP地址'),
    sa.Column('user_agent', sa.String(length=500), nullable=True, comment='用户代理'),
    sa.Column('success', sa.Boolean(), nullable=True, comment='是否登录成功'),
    sa.Column('failure_reason', sa.String(length=100), nullable=True, comment='失败原因'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='尝试时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_login_attempt_created', 'login_attempts', ['created_at'], unique=False)
    op.create_index('idx_login_attempt_email', 'login_attempts', ['email'], unique=False)
    op.create_index('idx_login_attempt_ip', 'login_attempts', ['ip_address'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False, comment='刷新令牌唯一标识符'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='用户ID'),
    sa.Column('token', sa.String(length=255), nullable=False, comment='刷新令牌'),
    sa.Column('access_token_version', sa.Integer(), nullable=False, comment='对应访问令牌版本'),
    sa.Column('revoked', sa.Boolean(), nullable=True, comment='是否已撤销'),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True, comment='撤销时间'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='过期时间'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_refresh_token', 'refresh_tokens', ['token'], unique=False)
    op.create_index('idx_refresh_token_expires', 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index('idx_refresh_token_user', 'refresh_tokens', ['user_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True)
    op.alter_column('password_reset_tokens', 'id',
               existing_type=sa.UUID(),
               comment='令牌唯一标识符',
               existing_nullable=False)
    op.alter_column('password_reset_tokens', 'user_id',
               existing_type=sa.UUID(),
               comment='用户ID',
               existing_nullable=False)
    op.alter_column('password_reset_tokens', 'token',
               existing_type=sa.VARCHAR(length=255),
               comment='重置令牌',
               existing_nullable=False)
    op.alter_column('password_reset_tokens', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='过期时间',
               existing_nullable=False)
    op.alter_column('password_reset_tokens', 'is_used',
               existing_type=sa.BOOLEAN(),
               comment='是否已使用',
               existing_nullable=True)
    op.alter_column('password_reset_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_password_reset_token', table_name='password_reset_tokens')
    op.drop_index('ix_password_reset_user', table_name='password_reset_tokens')
    op.create_index('idx_password_reset_token', 'password_reset_tokens', ['token'], unique=False)
    op.create_index('idx_password_reset_user', 'password_reset_tokens', ['user_id'], unique=False)
    op.add_column('users', sa.Column('login_attempts_count', sa.Integer(), nullable=True, comment='登录失败次数'))
    op.add_column('users', sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True, comment='账户锁定直到'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'locked_until')
    op.drop_column('users', 'login_attempts_count')
    op.drop_index('idx_password_reset_user', table_name='password_reset_tokens')
    op.drop_index('idx_password_reset_token', table_name='password_reset_tokens')
    op.create_index('ix_password_reset_user', 'password_reset_tokens', ['user_id'], unique=False)
    op.create_index('ix_password_reset_token', 'password_reset_tokens', ['token'], unique=False)
    op.alter_column('password_reset_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('password_reset_tokens', 'is_used',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否已使用',
               existing_nullable=True)
    op.alter_column('password_reset_tokens', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='过期时间',
               existing_nullable=False)
    op.alter_column('password_reset_tokens', 'token',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='重置令牌',
               existing_nullable=False)
    op.alter_column('password_reset_tokens', 'user_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='用户ID',
               existing_nullable=False)
    op.alter_column('password_reset_tokens', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='令牌唯一标识符',
               existing_nullable=False)
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.drop_index('idx_refresh_token_user', table_name='refresh_tokens')
    op.drop_index('idx_refresh_token_expires', table_name='refresh_tokens')
    op.drop_index('idx_refresh_token', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('idx_login_attempt_ip', table_name='login_attempts')
    op.drop_index('idx_login_attempt_email', table_name='login_attempts')
    op.drop_index('idx_login_attempt_created', table_name='login_attempts')
    op.drop_table('login_attempts')
    # ### end Alembic commands ###
