"""user profiles

Revision ID: 6360d3392535
Revises: d517faa26c91
Create Date: 2025-12-13 16:35:52.448106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6360d3392535'
down_revision: Union[str, Sequence[str], None] = 'd517faa26c91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('active_sessions',
    sa.Column('id', sa.UUID(), nullable=False, comment='会话唯一标识符'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='用户ID'),
    sa.Column('session_id', sa.String(length=255), nullable=False, comment='会话ID'),
    sa.Column('device_info', sa.String(length=500), nullable=True, comment='设备信息(JSON格式)'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='IP地址'),
    sa.Column('last_activity', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='最后活动时间'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='过期时间'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_active_session_expires', 'active_sessions', ['expires_at'], unique=False)
    op.create_index('idx_active_session_session', 'active_sessions', ['session_id'], unique=False)
    op.create_index('idx_active_session_user', 'active_sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_active_sessions_session_id'), 'active_sessions', ['session_id'], unique=True)
    op.create_table('user_preferences',
    sa.Column('id', sa.UUID(), nullable=False, comment='偏好设置唯一标识符'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='用户ID'),
    sa.Column('email_notifications', sa.Boolean(), nullable=True, comment='邮件通知'),
    sa.Column('push_notifications', sa.Boolean(), nullable=True, comment='推送通知'),
    sa.Column('marketing_emails', sa.Boolean(), nullable=True, comment='营销邮件'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('idx_preferences_user', 'user_preferences', ['user_id'], unique=False)
    op.add_column('users', sa.Column('display_name', sa.String(length=100), nullable=True, comment='显示名称'))
    op.add_column('users', sa.Column('avatar_url', sa.String(length=255), nullable=True, comment='头像URL'))
    op.add_column('users', sa.Column('timezone', sa.String(length=50), nullable=True, comment='时区'))
    op.add_column('users', sa.Column('language', sa.String(length=10), nullable=True, comment='语言偏好'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'language')
    op.drop_column('users', 'timezone')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'display_name')
    op.drop_index('idx_preferences_user', table_name='user_preferences')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_active_sessions_session_id'), table_name='active_sessions')
    op.drop_index('idx_active_session_user', table_name='active_sessions')
    op.drop_index('idx_active_session_session', table_name='active_sessions')
    op.drop_index('idx_active_session_expires', table_name='active_sessions')
    op.drop_table('active_sessions')
    # ### end Alembic commands ###
