"""add top10_float_holders table

Revision ID: 2a1ba1aca13f
Revises: 997425b1a9a8
Create Date: 2026-06-10 21:19:44.079904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2a1ba1aca13f'
down_revision: Union[str, Sequence[str], None] = '997425b1a9a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('top10_float_holders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('symbol', sa.String(length=10), nullable=False, comment='股票代码(纯数字,如600000)'),
    sa.Column('ts_code', sa.String(length=20), nullable=False, comment='Tushare代码(如600000.SH)'),
    sa.Column('report_period', sa.Date(), nullable=False, comment='报告期'),
    sa.Column('ann_date', sa.Date(), nullable=True, comment='公告日期'),
    sa.Column('holder_name', sa.String(length=100), nullable=False, comment='股东名称'),
    sa.Column('hold_amount', sa.Numeric(precision=20, scale=2), nullable=True, comment='持股数量(股)'),
    sa.Column('hold_ratio', sa.Numeric(precision=10, scale=4), nullable=True, comment='占总股本比例(%)'),
    sa.Column('hold_float_ratio', sa.Numeric(precision=10, scale=4), nullable=True, comment='占流通股本比例(%)'),
    sa.Column('hold_change', sa.Numeric(precision=20, scale=2), nullable=True, comment='持股变动'),
    sa.Column('holder_type', sa.String(length=50), nullable=True, comment='股东类型'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_top10_report_period', 'top10_float_holders', ['report_period'], unique=False)
    op.create_index('ix_top10_symbol_period', 'top10_float_holders', ['symbol', 'report_period'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### end Alembic commands ###
    op.drop_index('ix_top10_symbol_period', table_name='top10_float_holders')
    op.drop_index('ix_top10_report_period', table_name='top10_float_holders')
    op.drop_table('top10_float_holders')
    # ### end Alembic commands ###
