"""add fund tables

Revision ID: 997425b1a9a8
Revises: 02c292189ee0
Create Date: 2026-06-03 20:45:30.432458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '997425b1a9a8'
down_revision: Union[str, Sequence[str], None] = '02c292189ee0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fund_portfolio',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('fund_ts_code', sa.String(length=20), nullable=False, comment='基金TS代码'),
    sa.Column('report_period', sa.Date(), nullable=False, comment='报告期'),
    sa.Column('ann_date', sa.Date(), nullable=True, comment='公告日期'),
    sa.Column('stock_symbol', sa.String(length=20), nullable=False, comment='持仓股票代码(短码)'),
    sa.Column('market_value', sa.Numeric(precision=18, scale=2), nullable=True, comment='持仓市值(元)'),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True, comment='持仓数量(股)'),
    sa.Column('stk_mkv_ratio', sa.Numeric(precision=10, scale=4), nullable=True, comment='占股票市值比'),
    sa.Column('stk_float_ratio', sa.Numeric(precision=10, scale=4), nullable=True, comment='占流通股比'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_fund_portfolio_fund_period', 'fund_portfolio', ['fund_ts_code', 'report_period'], unique=False)
    op.create_index('ix_fund_portfolio_symbol_period', 'fund_portfolio', ['stock_symbol', 'report_period'], unique=False)
    op.create_table('funds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('ts_code', sa.String(length=20), nullable=False, comment='TS代码，唯一标识'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='基金名称'),
    sa.Column('management', sa.String(length=200), nullable=True, comment='管理人'),
    sa.Column('custodian', sa.String(length=200), nullable=True, comment='托管人'),
    sa.Column('fund_type', sa.String(length=50), nullable=True, comment='基金类型'),
    sa.Column('invest_type', sa.String(length=50), nullable=True, comment='投资类型'),
    sa.Column('benchmark', sa.String(length=500), nullable=True, comment='业绩比较基准'),
    sa.Column('market', sa.String(length=20), nullable=True, comment='市场类型: E 场内 O 场外'),
    sa.Column('found_date', sa.Date(), nullable=True, comment='成立日期'),
    sa.Column('list_date', sa.Date(), nullable=True, comment='上市日期'),
    sa.Column('delist_date', sa.Date(), nullable=True, comment='退市日期'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='状态: D 存续 I 发行 E 到期'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ts_code')
    )
    op.create_index('idx_funds_name', 'funds', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_funds_name', table_name='funds')
    op.drop_table('funds')
    op.drop_index('ix_fund_portfolio_symbol_period', table_name='fund_portfolio')
    op.drop_index('ix_fund_portfolio_fund_period', table_name='fund_portfolio')
    op.drop_table('fund_portfolio')
    # ### end Alembic commands ###
